version: 2.1

#
# Jobs
#

jobs:
  test:
    working_directory: *project_directory
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run:
          name: Test
          command: |
            set -o pipefail && xcodebuild -project LoopKit.xcodeproj -scheme Shared build -destination 'name=iPhone 16' test | xcpretty
      - store_test_results:
          path: test_output
  package:
    macos:
      xcode: 15.2.0
    steps:
      - checkout
      - run: rm -rf LoopKit.xcodeproj
      - run:
          name: Build LoopKit Package
          command: |
            set -o pipefail && xcodebuild build -scheme LoopKit -sdk iphonesimulator17.2 -destination "OS=17.2,name=iPhone 15" | xcpretty
      - run:
          name: Build LoopKitUI Package
          command: |
            set -o pipefail && xcodebuild build -scheme LoopKitUI -sdk iphonesimulator17.2 -destination "OS=17.2,name=iPhone 15" | xcpretty
#
# Workflows
#

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
      - package

